### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by bianyukun1213** [caryyu/maxsubtitle-openapi-server#1]
系统是 Windows 10 Enterprise LTSC 2021。

```
2022/01/13 22:30:28 listen on :3000
2022/01/13 22:30:53 http: panic serving [::1]:15608: open /tmp/data-cache/default-122304.srt: The system cannot find the path specified.
goroutine 6 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1802 +0xb9
panic({0x122d0a0, 0xc000365230})
        C:/Program Files/Go/src/runtime/panic.go:1047 +0x266
github.com/caryyu/subtitle-open-server/internal/resource.(*A4kDotNet).cacheFiles(0xc0002c8185, 0xc000068cb0)
        D:/Programs/maxsubtitle-openapi-server/internal/resource/A4kDotNet.go:300 +0x1b0
github.com/caryyu/subtitle-open-server/internal/resource.(*A4kDotNet).download(0x128abe3, {0xc0001ea53a, 0x6}, {0xc000109500, 0x77}, {0xc0002c8140, 0x0})
        D:/Programs/maxsubtitle-openapi-server/internal/resource/A4kDotNet.go:155 +0x6a5
github.com/caryyu/subtitle-open-server/internal/resource.(*A4kDotNet).Search(0x121f400, {0xc0001ba825, 0x5})
        D:/Programs/maxsubtitle-openapi-server/internal/resource/A4kDotNet.go:81 +0xf10
github.com/caryyu/subtitle-open-server/internal/handler.SearchHandler.func1({0x1318968, 0xc000056730}, 0xc0001b0480)
        D:/Programs/maxsubtitle-openapi-server/internal/handler/IndexHandler.go:41 +0x7e
net/http.HandlerFunc.ServeHTTP(0xc0001b6300, {0x1318968, 0xc000056730}, 0x10)
        C:/Program Files/Go/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001a4000, {0x1318968, 0xc000056730}, 0xc0001b6100)
        C:/Users/Hollis/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/gorilla/handlers.loggingHandler.ServeHTTP({{0x1311e60, 0xc000006018}, {0x1311560, 0xc0001a4000}, 0x12b19b8}, {0x1318458, 0xc0001907e0}, 0xc0001b6100)
        C:/Users/Hollis/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/logging.go:47 +0xef
net/http.serverHandler.ServeHTTP({0xc0001b0300}, {0x1318458, 0xc0001907e0}, 0xc0001b6100)
        C:/Program Files/Go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0001b20a0, {0x131a268, 0xc0001b0210})
        C:/Program Files/Go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        C:/Program Files/Go/src/net/http/server.go:3034 +0x4e8
exit status 0xc000013a
```

**Comment by caryyu** [comment]
默认字幕会被下载进目录 `/tmp/data-cache` （该目录可以利用环境变量覆盖）； 你可以参考这里设置：
https://github.com/caryyu/maxsubtitle-openapi-server/blob/8372f10cec16ea553d526215a6c13a700b1fff76/cmd/server/main.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L17

**Comment by bianyukun1213** [comment]
在 Windows 下还会报 `open /tmp/data.bin: The system cannot find the path specified.` 错误。

**Comment by caryyu** [comment]
@bianyukun1213 这里有一个 Bug ，可以考虑使用上述的方式扩展一个环境变量出来解决：
https://github.com/caryyu/maxsubtitle-openapi-server/blob/main/internal/resource/A4kDotNet.go#L206

**Comment by caryyu** [comment]
@bianyukun1213 上述 Bug 已经在最新的代码中得到了修复，可以使用最新的代码再次尝试一下，谢谢。
