### ISSUE TITLE
获取字幕的时候总是500错误

### ISSUE THREAD

**Issue by fopiko** [caryyu/maxsubtitle-openapi-server#5]
是因为被限制了吗？

**Comment by caryyu** [comment]
@fopiko 服务端的报错日志方便上传上来看看嘛？

**Comment by fopiko** [comment]
[2022-05-12 22:45:09.757 +08:00] [INF] [Max Subtitle] Search of [name]: "mr.bean.e12.blind.date.480p.web.aac2.0.h264-lightspeed"
[2022-05-12 22:45:10.699 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2022-05-12 22:45:10.699 +08:00] [INF] [Max Subtitle] Search of [name]: "mr.bean.e12.blind.date.480p.web.aac2.0.h264-lightspeed"
[2022-05-12 22:45:11.044 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2022-05-12 22:45:11.046 +08:00] [INF] [Max Subtitle] Search of [name]: "mr.bean.e12.blind.date.480p.web.aac2.0.h264-lightspeed"
[2022-05-12 22:45:11.351 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2022-05-12 22:45:18.608 +08:00] [INF] [Max Subtitle] Search of [name]: "Young.Sheldon.S04E13"
[2022-05-12 22:45:19.148 +08:00] [INF] [Max Subtitle] Search of [name]: "mr.bean.e13.do.it.yourself.mr.bean.pal.dvd.dd2.0.x264hi10-lightspeed"
[2022-05-12 22:45:20.510 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2022-05-12 22:45:21.081 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2022-05-12 22:45:21.083 +08:00] [INF] [Max Subtitle] Search of [name]: "mr.bean.e13.do.it.yourself.mr.bean.pal.dvd.dd2.0.x264hi10-lightspeed"
[2022-05-12 22:45:21.382 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2022-05-12 22:45:21.385 +08:00] [INF] [Max Subtitle] Search of [name]: "mr.bean.e13.do.it.yourself.mr.bean.pal.dvd.dd2.0.x264hi10-lightspeed"
[2022-05-12 22:45:21.523 +08:00] [INF] [Max Subtitle] Search of [name]: "Young.Sheldon.S04E13"
[2022-05-12 22:45:21.685 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2022-05-12 22:45:21.806 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2022-05-12 22:45:21.838 +08:00] [INF] [Max Subtitle] Search of [name]: "Young.Sheldon.S04E13"
[2022-05-12 22:45:22.143 +08:00] [ERR] Error downloading subtitles from "MaxSubtitle"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.MaxSubtitle.MastApiClient.Search(String keyword, CancellationToken cancellationToken)
   at Jellyfin.Plugin.MaxSubtitle.MastSubtitleProvider.Search(SubtitleSearchRequest info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)

**Comment by caryyu** [comment]
@fopiko 这个是客户端日志，你得看服务端日志。

**Comment by fopiko** [comment]
这是没有搜索到字幕的原因吗

2022/05/14 12:37:34 element `ul` with attributes `class ui relaxed divided list` not found
172.17.0.1 - - [14/May/2022:12:37:33 +0000] "GET /subtitle/search/%E8%8D%AF%E7%98%BE HTTP/1.1" 500 26
2022/05/14 12:37:34 element `ul` with attributes `class ui relaxed divided list` not found
172.17.0.1 - - [14/May/2022:12:37:34 +0000] "GET /subtitle/search/%E8%8D%AF%E7%98%BE HTTP/1.1" 500 26
2022/05/14 12:37:35 element `ul` with attributes `class ui relaxed divided list` not found
172.17.0.1 - - [14/May/2022:12:37:35 +0000] "GET /subtitle/search/%E8%8D%AF%E7%98%BE HTTP/1.1" 500 26
172.17.0.1 - - [14/May/2022:12:37:36 +0000] "GET /subtitle/search/%E5%96%84%E6%81%B6%E6%97%A0%E8%B5%A6 HTTP/1.1" 500 26
2022/05/14 12:37:37 element `ul` with attributes `class ui relaxed divided list` not found
172.17.0.1 - - [14/May/2022:12:37:37 +0000] "GET /subtitle/search/%E5%96%84%E6%81%B6%E6%97%A0%E8%B5%A6 HTTP/1.1" 500 26
2022/05/14 12:37:38 element `ul` with attributes `class ui relaxed divided list` not found
2022/05/14 12:37:39 element `ul` with attributes `class ui relaxed divided list` not found

**Comment by caryyu** [comment]
@fopiko 爬虫出问题了，服务端需要修正，应该是找不到结果之后获取 HTML 标签出错导致。

**Comment by fopiko** [comment]
@caryyu 是需要等你更新然后重新拉取镜像吗

**Comment by caryyu** [comment]
@caryyu 已经修复了，你可以把最新的变更镜像拉取下来再次测试，谢谢。

**Comment by fopiko** [comment]
@caryyu 经测试 暂不见错误，谢谢修复
